// Auto-generated by scrape-ssjcoe.py
// Do not edit manually
// Paths use /images/images/ because files live under public/images/images/

const P = "/images/images";

export const IMAGES = {
  "logo": "/images/logo.png",
  "dept_it": `${P}/depts/Information-technology.jpg`,
  "dept_cs": `${P}/depts/Computerl-Engineering.jpg`,
  "dept_mech": `${P}/depts/Mechanical-Engineering.jpg`,
  "dept_entc": `${P}/depts/Electronics-Telecomm.-Engineering.jpg`,
  "dept_chem": `${P}/depts/Chemical-Engineering.jpg`,
  "dept_aiml": `${P}/depts/AI-and-Machine-Learning.jpg`,
  "achievement_sih": `${P}/achievements/New-SIH-GRAND-FINAL_1.jpg`,
  "achievement_nec": `${P}/achievements/New-Our-students-have-secured-a-position-in-the-Top-7-at-the-NEC-organised-by-IIT-Bombay-competing-among-4000-colleges-nationwide.jpg`,
  "campus_ict": `${P}/campus/ICT.jpg`,
  "campus_sports": `${P}/campus/Sports-2025.jpg`,
  "campus_ai": `${P}/campus/E-cell-event-ASPIRO2025.jpg`,
  "recruiter_godrej": `${P}/recruiters/Godrej.jpg`,
  "recruiter_infosys": `${P}/recruiters/Infosys.jpg`,
  "recruiter_wipro": `${P}/recruiters/Wipro.jpg`,
  "recruiter_tata": `${P}/recruiters/Tata.jpg`,
  "recruiter_capgemini": `${P}/recruiters/Capgemini.jpg`,
  "recruiter_accenture": `${P}/recruiters/accenture.jpg`,
  "recruiter_lt": `${P}/recruiters/LT-Infotech.jpg`,
} as const;

export const DEPT_IMAGES: Record<string, string> = {
  IT: `${P}/depts/Information-technology.jpg`,
  CS: `${P}/depts/Computerl-Engineering.jpg`,
  MECH: `${P}/depts/Mechanical-Engineering.jpg`,
  ENTC: `${P}/depts/Electronics-Telecomm.-Engineering.jpg`,
  CHEM: `${P}/depts/Chemical-Engineering.jpg`,
  AIML: `${P}/depts/AI-and-Machine-Learning.jpg`,
};

export const RECRUITER_LOGOS = [
  { name: "Godrej", logo: `${P}/recruiters/Godrej.jpg` },
  { name: "Infosys", logo: `${P}/recruiters/Infosys.jpg` },
  { name: "Wipro", logo: `${P}/recruiters/Wipro.jpg` },
  { name: "Tata", logo: `${P}/recruiters/Tata.jpg` },
  { name: "Capgemini", logo: `${P}/recruiters/Capgemini.jpg` },
  { name: "Accenture", logo: `${P}/recruiters/accenture.jpg` },
  { name: "L&T Infotech", logo: `${P}/recruiters/LT-Infotech.jpg` },
  { name: "Worley Parsons", logo: `${P}/recruiters/Worley-parsons.jpg` },
  { name: "NSE", logo: `${P}/recruiters/NSE.jpg` },
];
